name: Flutter Executable Builds

on:
  push:
    tags:
      - 'v*.*.*@stable'
      - 'v*.*.*@unstable'
      - 'v*.*.*@experimental' # same as unstable but "stable" but some things may not work but not too unstable
jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: windows-exe
          path: build/windows/runner/Release/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          paths: 
            - build/windows/runner/Release
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
