name: Flutter Executable Builds

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Build Windows

      - name: Upload Executable Bundle
        uses: actions/upload-artifact@v4
        with:
          path: |
            build/windows/runner/Release/