name: Flutter Executable Builds

on:
  push:
    branches:
      - main
      - development # todo: actually create this branch later
    tags:
      - 'release.[1-9].[0-9]?.[0-9]?.[0-9]?-[us]' # format: release.<maj>.<min>.<patch>.<subpatch>-<u or s>

jobs:
  build-windows:
    name: Build Windows EXE
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows EXE
        run: flutter build windows --release

      - name: Zip Executable Output
        run: |
          powershell Compress-Archive `
            -Path build/windows/x64/runner/Release/* `
            -DestinationPath windows-exe.zip

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: windows-exe.zip
          tag_name: ${{ github.ref_name }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: write
